apiVersion: v1
kind: Secret
metadata:
  name: password-secret
  labels:
     {{- include "KIU_Challenge.labels" . | nindent 4 }}
type: Opaque
data:
  PASSWORD: {{ .Files.Get "rds-secret/password" | b64enc | quote }}